apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deploy
  namespace: static
spec:
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      name: static-pod
      labels:
        app: static
    spec:
      containers:
      - name: staticcont
        image: 311508566714.dkr.ecr.us-east-2.amazonaws.com/staticweb:1
        ports:
        - containerPort: 80
